### ISSUE TITLE
make `theme_grattan()` complete 

### ISSUE THREAD

**Issue by MattCowgill** [MattCowgill/grattantheme#108]
```
> base_plot <- mtcars %>%
+   ggplot(aes(x = wt,
+              y = mpg)) +
+   geom_point() +
+   labs(title = "Here goes a Grattan title, blah blah lots of words go here extremely orange",
+        caption = "Notes: Blah Source: somewhere")
> normal_plot <- base_plot +
+   theme_grattan() +
+   labs(subtitle = "Either put units here or jam an elaborate thing here that describes both axes, whatevs")
> normal_plot
Error in Ops.unit(non_position_panel, (tick_direction * tick_length)) : 
  both operands must be units
```

**Comment by MattCowgill** [comment]
```
> packageVersion("ggplot2")
[1] ‘3.2.1.9000’
```

**Comment by wfmackey** [comment]
I'll fix today

**Comment by MattCowgill** [comment]
taaaaaa

**Comment by wfmackey** [comment]
QUESTION: should `grattan_theme` really be using the dev version of `ggplot2`?

**Comment by MattCowgill** [comment]
no & it isn't! By default it imports the CRAN version of ggplot2. The package is still passing all tests on Travis, using CRAN ggplot2.

But I'm running the dev version of ggplot2 (& other tidyverse packages) on my local machine. This likely reflects some change to ggplot2 that will eventually be incorporated into the CRAN version, so better to fix it now

**Comment by MattCowgill** [comment]
NOTE TO SELVES: this seems to be related to recent changes to ggplot2 (see https://github.com/tidyverse/ggplot2/pull/3570). 

These changes are not yet in the CRAN version of ggplot2. We'll stick to CRAN ggplot2 for now and fix the problem in grattantheme when CRAN ggplot2 is updated, if the problem persists.

**Comment by MattCowgill** [comment]
FURTHER NOTE TO SELVES: when fixing this, do #37

**Comment by MattCowgill** [comment]
I just tried with the latest Github version of `ggplot2` and the new CRAN release of `scales`. 

`theme_grattan()` no longer throws an error, but the visual unit tests fail - the plot background is now grey rather than white. I'll puzzle through this when I get time. For now, everything remains fine if you use the CRAN release of ggplot2.

**Comment by MattCowgill** [comment]
I think the solution to this is going to be either:

1) base `theme_grattan()` on a complete theme, rather than `theme_foundation()`; OR

2) continue to base `theme_grattan()` on `theme_foundation()`, but make it truly complete (ie. ensure that all elements in the theme tree are defined)

**Comment by MattCowgill** [comment]
I think option 1 is the best, I will do this when I have time (post-report)

**Comment by wfmackey** [comment]
Yep option one is best

**Comment by MattCowgill** [comment]
note to self: check out `cowplot::theme_minimal_hgrid()` and see how it’s constructed
