### ISSUE TITLE
Legend titles removed by theme_grattan() when legend != "none"

### ISSUE THREAD

**Issue by wfmackey** [MattCowgill/grattantheme#13]
Legend titles are removed by `theme_grattan()` via (I think?)  `legend.title = ggplot2::element_blank()`.

For cases in which `theme_grattan(legend = "top")` (or != "none"), should the legend title be turned back on?

_AND_, coding-wise, would this be done by:

```
legend_title <- ggplot2::element_blank()
if (legend != "none" & legend != "off") legend_title <- ggplot2::element_blank()

ret <-
...
    legend.title = legend_title,
    panel.border = ggplot2::element_blank(),
```

**Comment by MattCowgill** [comment]
I don't have a strong view about whether to do this or not - go for it if you want. 
No need to add that code - if you just delete the 
`legend.title  = element_blank()` 
line then the legend title should show when legend != "none. When legend == "none" (the default) the legend title will still be blank.

Note: you might also need to delete `legend.title.align = NULL`

**Comment by MattCowgill** [comment]
MY TAKE, AS DISCUSSED: yeah, nah
