### ISSUE TITLE
Wait -- what's the go with zero-aligned x-axis for geom_bar again?

### ISSUE THREAD

**Issue by wfmackey** [MattCowgill/grattantheme#15]
I think you have addressed this **and** explained it to me, but:

How do I get the x axis to start at zero for bar charts with `theme_grattan`?

**Comment by MattCowgill** [comment]
+scale_y_continuous_grattan() 

I’m open to either different names for this (grattan_scale_continuous() ? ) or different ways to implement this change

**Comment by wfmackey** [comment]
Added a note about `scale_y_continuous_grattan()` in #17

**Comment by wfmackey** [comment]
Maybe given `scale_colour_manual` -> `grattan_colour_manual` and `scale_fill_manual` -> `grattan_fill_manual` our go-to should be replacing `scale` with `grattan`? eg

`scale_y_continuous` -> `grattan_y_continuous`
`scale_x_continuous` -> `grattan_x_continuous`

If okay, I will implement now with backward compatibility for `scale_y_continuous_grattan`.
