### ISSUE TITLE
Vignette is breaking the travis build

### ISSUE THREAD

**Issue by wfmackey** [MattCowgill/grattantheme#18]
I'm looking into this now. The error suggests it is a size issue (too many charts?).

**Comment by wfmackey** [comment]
Hm. The package works, and the vignette can be called normally using 

`vignette("using_grattantheme", package = "grattantheme")`

**Comment by MattCowgill** [comment]
No worries, fixing it can wait! 

Does it pass if you run devtools::check() locally?

**Comment by MattCowgill** [comment]
Fixed already I see 👍

**Comment by wfmackey** [comment]
Continuous checking via Travis is fantastic and STRESSFUL. I love it.
