### ISSUE TITLE
remove height and width options in grattan_save()

### ISSUE THREAD

**Issue by MattCowgill** [MattCowgill/grattantheme#27]
I think maybe we should remove the `height` and `width` arguments to `grattan_save()`. The `type` argument already does the work here.  

What do you think @wfmackey?

**Comment by wfmackey** [comment]
Yep I agree. Height/width can still be passed through via `...` if needed.

**Comment by MattCowgill** [comment]
done in https://github.com/MattCowgill/grattantheme/commit/c7f7944e1de58b2280914b62e89a044cd775f360

doesn't take dots for now
