### ISSUE TITLE
add option to save multiple chart types at the same time 

### ISSUE THREAD

**Issue by MattCowgill** [MattCowgill/grattantheme#35]
when type = “all”, grattan_save() should create a subdir containing images with the graph in all formats

**Comment by MattCowgill** [comment]
Might do this as a new function - grattan_save_all() ?

What you think @wfmackey

**Comment by wfmackey** [comment]
Great idea. But nah I think type = "all" is better (rather than having to remember more functions). 
Should have savedata = TRUE as default when type = "all" and store it in the subdir too.

**Comment by MattCowgill** [comment]
yeah fair enough. What should grattan_save() take as the `filename` argument if `type="all"`? A path to a directory?

**Comment by wfmackey** [comment]
Leave as is and strip the `.pdf` if it's included. So:
```
grattan_save("doubleyaxischart.pdf", type = "all")
```
would create a folder called `doubleyaxischart` and fill it with
```
> doubleyaxischart
>> doubleyaxischart_fullslide.pdf
>> doubleyaxischart_fullslide169.pdf
>> doubleyaxischart_normal.pdf
...
>> doubleyaxischart_chartdata.csv
```

**Comment by MattCowgill** [comment]
sold @wfmackey, will do

**Comment by MattCowgill** [comment]
DOUBLEYAXISCHART I SEE WHAT YOU DID THERE

**Comment by MattCowgill** [comment]
done in `save-all` branch; `grattan_save()` is getting a little (unnecessarily?) unwieldy; I'm open to ideas about how to streamline it. The documentation could also be improved.
