### ISSUE TITLE
add gganimate support to grattan_save

### ISSUE THREAD

**Issue by jonathananolan** [MattCowgill/grattantheme#39]
It would be nice to add gganimate support to grattan save

**Comment by MattCowgill** [comment]
good idea @jonathananolan - happy to review a pull request

**Comment by wfmackey** [comment]
@MattCowgill was just about to make that joke

**Comment by MattCowgill** [comment]
so I looked into this - gganimate objects don't work with gridExtra::grid.arrange(), which means that the way fullslide is currently implemented wouldn't work with gganimate animations. The package author has said he intends to add support for patchwork (his alternative to gridExtra) at some point (https://github.com/thomasp85/gganimate/issues/86) but this hasn't happened yet.

The only way I can see to make this work would be to use annotation_custom() to add the Grattan logo and orange line, and then tweak the theme to add whitespace, resize the title, etc. This might be possible but would be fiddly.

**Comment by MattCowgill** [comment]
discussed with @jonathananolan, decided to abandon this

**Comment by MattCowgill** [comment]
reconsidering this, maybe using the .Rmd approach in make_slide()

**Comment by MattCowgill** [comment]
possible approach: https://stackoverflow.com/questions/55362961/using-a-gtable-object-with-gganimate

**Comment by MattCowgill** [comment]
I have this working in a clunky interactive script but integrating it into the package will be a challenge. I'll need to think about whether it's worth the hassle and, if so, how best to do it.
