### ISSUE TITLE
Add blog image template to grattan_save()

### ISSUE THREAD

**Issue by MattCowgill** [MattCowgill/grattantheme#50]
4:3, but with reduced margins

Subject to JD approval

**Comment by MattCowgill** [comment]
@wfmackey I'm planning to add a a `type = "blog"` type (default size: same as 4:3 but with less whitespace) and a `height` argument to `grattan_save()`. `height` will be NULL by default, which means `grattan_save()` will use the default height for the chart type. When `height` is specified, this will override the default for the chart type. Not planning to add a `width` argument. Does that sound alright?

**Comment by wfmackey** [comment]
Yep love it!
