### ISSUE TITLE
Should grattantheme replace geom_label() etc?

### ISSUE THREAD

**Issue by MattCowgill** [MattCowgill/grattantheme#64]
We generally want labels without lines and with narrow padding. Should we overwrite geom_label() and geom_text() to make these the defaults? See https://github.com/tidyverse/ggplot2/issues/3392#issuecomment-508793813

@wfmackey

**Comment by wfmackey** [comment]
We can talk about it WHEN YOU FINISH YOUR HOLIDAY.

**Comment by MattCowgill** [comment]
g'day @wfmackey

**Comment by wfmackey** [comment]
Hi Matt welcome back. So the idea is to overwrite `geom_label` and `geom_text` when `theme_grattan` is used?

**Comment by MattCowgill** [comment]
yeah nah let's leave it I guess. We've got the `update_geom_defaults()` function which runs silently when `theme_grattan()` is run. The only issue is that this doesn't / can't remove the border from labels and reduce their padding. But on thinking it through let's leave it
