### ISSUE TITLE
rewrite palette to make it more flexible

### ISSUE THREAD

**Issue by MattCowgill** [MattCowgill/grattantheme#65]
see https://drsimonj.svbtle.com/creating-corporate-colour-palettes-for-ggplot2

**Comment by wfmackey** [comment]
Love it. Can I do it?

**Comment by MattCowgill** [comment]
Yes pls!

**Comment by MattCowgill** [comment]
I think we should still have the colours (`grattan_red` etc.) as individual objects available to the user, but also create these named vectors for use in the palette function

**Comment by wfmackey** [comment]
Yep.
