### ISSUE TITLE
Should light orange and red be the default colours for two discrete categories?

### ISSUE THREAD

**Issue by MattCowgill** [MattCowgill/grattantheme#79]
`grattan_pal(n = 2)` (and therefore `grattan_colour_manual(n = 2)` returns light orange and dark orange.

`grattan_pal(n = "2a")` returns light orange and red. I added this option because I prefer using these colours for a two-group discrete series rather than light and dark orange. @wfmackey has the opposite, wrong, view. 

I'm interested in whether: a) other Grattanites agree with my preference, and if so b) whether `2` should give light orange and red, while `2a` gives Will's preferred indistinguishable gradients of orange.

**Comment by LucyPercival** [comment]
light orange and red don't mix well in a crowded room. Good friends only in a bar environment.

(why is my photo literally as a latte sipper?)

**Comment by MattCowgill** [comment]
Wait - I'm confused about which you prefer now

**Comment by MattCowgill** [comment]
seeking views @jonathananolan @owainemslie @carmelachivers1 @k-griffiths @gregmoran @jamesha95

**Comment by wfmackey** [comment]
No.

**Comment by LucyPercival** [comment]
I like light orange and red for bar charts. But for scatters they are impossible to distinguish

**Comment by MattCowgill** [comment]
We can't have different defaults in `grattan_colour_manual()` for different chart types @LucyPercival - there has to be one default and then you can override it if you want

**Comment by MattCowgill** [comment]
THE MOTION IS CARRIED ON THE VOICES

**Comment by OwainEmslie** [comment]
Hey, don't close the issue - it took me this long to work out how to reply on github!

Now I have to work out how to add Dan Petrie to this thread - I'll vote with whatever he reckons.

**Comment by MattCowgill** [comment]
Will's side has already lost, but just for posterity:

**Option A**![image](https://user-images.githubusercontent.com/8002951/62753308-787c5200-baae-11e9-98fa-d56b43361ded.png)

**Option B**
![image](https://user-images.githubusercontent.com/8002951/62753326-8af68b80-baae-11e9-8928-2b1c34d5bfd9.png)

**Comment by k-griffiths** [comment]
Option B is definitely easier to read and has always been the default for two-colour charts.

**Comment by MattCowgill** [comment]
Another vote for Option B! So far a grand total of 0 people have agreed with Will

**Comment by jamesha95** [comment]
…While I stand by Option B – especially for highlighting a singular data point – I do think Option A is aesthetically soothing when there’s a bunch of rows in each group… **ducks**

**Comment by wfmackey** [comment]
Correct @jamesha95 ! Case closed!

**Comment by k-griffiths** [comment]
You guys seem to think this is a democracy? No point thrashing it out here, pull together your cases and pitch them to the Dictator of Style.

**Comment by MattCowgill** [comment]
Email from JD: "I like the red.  Prints out better in black and white."

The motion is carried
