### ISSUE TITLE
expand plot vertically to fill space when subtitle/units is absent in fullslide plots

### ISSUE THREAD

**Issue by MattCowgill** [MattCowgill/grattantheme#80]
I will do this for animated plots. Should I also do it for static fullslide/blog/etc type plots @wfmackey?

**Comment by wfmackey** [comment]
Depends if we want to _allow_ people to have charts without units. I guess we should.

**Comment by MattCowgill** [comment]
Not sure - but I don't really see a reason to treat animated charts different from static charts?

**Comment by wfmackey** [comment]
Yeah I think we should enable it for both.

**Comment by MattCowgill** [comment]
righto
