### ISSUE TITLE
enable the use of ggtext in titles + subtitles of fullslide plots

### ISSUE THREAD

**Issue by MattCowgill** [MattCowgill/grattantheme#86]
[ggtext](https://github.com/clauswilke/ggtext) enables you to (among other things) colour individual words in a title/subtitle that correspond to series in the data, in lieu of a legend. This works with `grattan_save()` when saving a non-fullslide type plot, such as `type = "normal", force_labs = TRUE`. It doesn't work with fullslide plots (including blog, etc.)

**Comment by MattCowgill** [comment]
@wfmackey do you think this is worth adding?

**Comment by MattCowgill** [comment]
pros: it's good, cool, etc
cons: may be slightly fiddly to implement, adds a dependency to a (possibly not-yet-stable) another package

**Comment by wfmackey** [comment]
I agree with the pros. But Paul is pretty against it! (I tried it in our latest report).

But: we can get him onside; and it would be cool to have. 

BUT: probably worth focussing on R_at_grattan for now. Maybe bench it until one of us actually wants to use it for something -- then we can generalise it for `grattantheme`.

**Comment by MattCowgill** [comment]
Oh that's a shame that Paul doesn't like it! What was his reasoning.

Yep agreed let's put it on the backburner for now. I'll leave the issue open.

**Comment by wfmackey** [comment]
He doesn't like coloured text that isn't strictly on a chart, ie titles and subtitles should be consistently grey. 

I think I got his guard up by first approaching him about having colour-coded words in a paragraph next to the chart; which, to be fair, might be a stretch (although I like it).

**Comment by MattCowgill** [comment]
duplicated in #105
