### ISSUE TITLE
Allow overriding of expand arguments in grattan_y_continuous

### ISSUE THREAD

**Issue by wfmackey** [MattCowgill/grattantheme#92]
`grattan_y_continuous` is good, but annoying when you decide to expand the y-axis and have to switch back to `scale_y_continuous`. 

(this issue mainly comes from drafting the Data Viz section of R at Grattan -- but alludes to a fair point)

A provided `expand` argument should override the default `expand` operation in  `grattan_y_continuous`.

**Comment by MattCowgill** [comment]
`grattan_y_continuous` already has expand_bottom and expand_top arguments. 

Do you mean you want an additional logical argument that sets the expand value equal to the scale_y_continuous defaults?

**Comment by wfmackey** [comment]
Nah nah all good.
