### ISSUE TITLE
Different layout for scatterplots?

### ISSUE THREAD

**Issue by wfmackey** [MattCowgill/grattantheme#97]
Making an DVC-executive call and saying that we should change how Grattan presents scatter plots. Mainly: both axes black, gridlines both ways, _allow_ a y-axis title if desired. 

1) Thoughts?
2) Would this require a different theme, ie `theme_grattan_scatter`? Or possible just with an `grattan_y_continuous` argument?

![image](https://user-images.githubusercontent.com/30094143/64655036-5f304200-d46e-11e9-97b1-3a3932d6e758.png)

**Comment by MattCowgill** [comment]
1. This is bold, you've gone mad with power. We all knew this day was coming.
2. I like the dual black lines and gridlines both ways; I don't like the minor gridlines.
3. `theme_grattan()` doesn't know what type of geoms you've used, so this can't work automatically. Two (non-mutually-exclusive) options: 

a) add a `scatter` argument to `theme_grattan()`, so `theme_grattan(scatter = TRUE)` gives you this theme
b) add a `theme_grattan_scatter()`.

It would be easy to do both of these things.

**Comment by MattCowgill** [comment]
so, to recap:

`theme_grattan()` remains the main function called by users; it returns a different theme object depending on the value of the `type` argument

if `type = "normal"` (the default), `theme_grattan()` returns the normal theme using `theme_grattan_normal()`

if `type = "scatter"`, `theme_grattan()` returns the scatterplot theme using `theme_grattan_scatter()`

The `theme_grattan_*()` functions can be exported if you want - but I think users should usually interact with them using the `type` argument of `theme_grattan()`

Agreed?

**Comment by wfmackey** [comment]
Agreed. Don't think we should export the `theme_grattan_*`s -- just give users one correct way to do something.

**Comment by MattCowgill** [comment]
Yep, cool. Do you mind doing this? You could add `theme_grattan_map()` or whatever as well if you can be bothered

**Comment by wfmackey** [comment]
Yep doing now

**Comment by wfmackey** [comment]
lol are you subtweeting (subtesting?) Brendan?: 'labs(subtitle = "Either put units here or jam an elaborate thing here that describes both axes, whatevs")

**Comment by MattCowgill** [comment]
lol

**Comment by MattCowgill** [comment]
closed in https://github.com/MattCowgill/grattantheme/pull/99
